[[rule]]
include = [
    ".taplo.toml",
    "taplo.toml",
    ".stylua.toml",
    "stylua.toml",
    "**/alacritty.toml",
    "**/config.toml",
    "**/starship.toml",
    "**/yazi.toml",
    "**/theme.toml",
]
exclude = ["config/yazi/themes/**", "config/alacritty/themes/**", "submods/**"]

[rule.formatting]
align_entries = true
align_comments = true
array_trailing_comma = true
trailing_newline = true
column_width = 100
inline_table_expand = false
