#!/bin/zsh

##? br - start broot and execute the command it produces
##?
##? usage:
##?   br [broot-options] [path]
##?
##? examples:
##?   br                    # start broot in current directory
##?   br ~/projects         # start broot in ~/projects
##?   br -h                 # show broot help

br() {
  [[ "$1" == "-h" || "$1" == "--help" ]] && { grep "^##?" "${(%):-%x}" | cut -c 5-; return 0; }

  local cmd cmd_file code

  cmd_file=$(mktemp)

  if broot --outcmd "$cmd_file" "$@"; then
    cmd=$(<"$cmd_file")
    command rm -f "$cmd_file"
    eval "$cmd"
  else
    code=$?
    command rm -f "$cmd_file"
    return "$code"
  fi
}

# vim: ft=zsh
