#!/bin/zsh

##? brew_rebuild  - rebuild cache for various brew packages
##?
##? usage:
##?   brew_rebuild

brew_rebuild() { 
	printf ">>> updating bat cache...\n"
	bat cache --build
	printf ">>> bat cache updated...\n"
	printf "\n"
	printf ">>> updating tldr cache...\n"
	tldr --update
	printf ">>> tldr cache updated...\n"
}

# vim: ft=zsh