#!/bin/zsh

##? colormap - print a quick terminal colormap (256 colors)
##?
##? usage:
##?   colormap

colormap() {
  [[ "$1" == "-h" || "$1" == "--help" ]] && { grep "^##?" "${(%):-%x}" | cut -c 5-; return 0; }

  local i
  for i in {0..255}; do
    print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'}
  done
}

# vim: ft=zsh
