#!/bin/zsh

##? ffc  - fetch system settings using fastfetch, output and copy to clipboard
##?
##? usage:
##?   ffc

# TODO: add more options, e.g. `R`/`python` versions etc.
# TODO: consider a --details option to wrap output in summary/details html tags
ffc() {
    fastfetch | tee >(pbcopy)
}

# vim: ft=zsh