#!/bin/zsh

##? gi - create gitignore file for single/multiple languages
##?
##? usage:
##?   gi <lang[,lang,...]>
##?
##? examples:
##?   gi macos,R,Python,VisualStudioCode >> .gitignore

gi() {
  [[ "$1" == "-h" || "$1" == "--help" ]] && { grep "^##?" "${(%):-%x}" | cut -c 5-; return 0; }

  curl -sLw n "https://www.toptal.com/developers/gitignore/api/$@"
}

# vim: ft=zsh
