#!/bin/zsh

##? k - wrapper for zk (zettelkasten) with optional template sync
##?
##? usage:
##?   k [--sync-templates] [zk-command] [args...]
##?
##? options:
##?   --sync-templates  sync templates from dotfiles to Dropbox before running zk
##?
##? examples:
##?   k daily                    # create/open today's journal entry
##?   k --sync-templates idea    # sync templates, then create idea
##?   k edit                     # edit a note interactively

k() {
  [[ "$1" == "-h" || "$1" == "--help" ]] && { grep "^##?" "${(%):-%x}" | cut -c 5-; return 0; }

  local sync_templates=false

  if [[ "$1" == "--sync-templates" ]]; then
    sync_templates=true
    shift
  fi

  if [[ "$sync_templates" == true ]]; then
    rsync -au --delete \
      ~/.config/zk/templates/ \
      ~/DROPBOX/notes/zk/.zk/templates/ 2>/dev/null
  fi

  command zk "$@"
}

# vim: ft=zsh
