#!/bin/zsh

##? rmt - move a file or directory to macOS Trash directory
##?
##? usage:
##?   rmt <file|dir>

rmt() {
  [[ "$1" == "-h" || "$1" == "--help" ]] && { grep "^##?" "${(%):-%x}" | cut -c 5-; return 0; }

  mv -f "$1" "${HOME}/.Trash"
}

# vim: ft=zsh
