#!/bin/zsh

##? tmux-resize  - ensure tmux window has correct dimensions before
##?                launching a fullscreen TUI app. No-op outside tmux.
##?
##? usage:
##?   tmux-resize

tmux-resize() {
	[[ -n "$TMUX" ]] && tmux resize-window -A
}

# vim: ft=zsh
