#!/bin/zsh

##? tmux-resize - ensure tmux window has correct dimensions before
##?               launching a fullscreen TUI app. No-op outside tmux.
##?
##? usage:
##?   tmux-resize

tmux-resize() {
  [[ "$1" == "-h" || "$1" == "--help" ]] && { grep "^##?" "${(%):-%x}" | cut -c 5-; return 0; }

  [[ -n "$TMUX" ]] && tmux resize-window -a
}

# vim: ft=zsh
