#!/bin/zsh

##? y - shell wrapper that provides the ability to change the current working
##?     directory when exiting yazi.
##?
##? usage:
##?   y

y() {
  [[ "$1" == "-h" || "$1" == "--help" ]] && { grep "^##?" "${(%):-%x}" | cut -c 5-; return 0; }

  local tmp cwd
  tmp="$(mktemp -t "yazi-cwd.XXXXXX")"

  tmux-resize
  yazi "$@" --cwd-file="$tmp"

  if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
    builtin cd -- "$cwd"
  fi
  rm -f -- "$tmp"

  clear
}

# vim: ft=zsh
