#!/bin/zsh

##? y  - shell wrapper that provides the ability to change the current working 
##?      directory when exiting Yazi.
##?
##? usage:
##?   y

y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	[[ -n "$TMUX" ]] && tmux resize-window -A
	yazi "$@" --cwd-file="$tmp";
	if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		builtin cd -- "$cwd"
	fi
	rm -f -- "$tmp"

  # clear screen after quitting yazi
  clear 
}

# vim: ft=zsh
