# Using the Tokyo Night Preset Color theme
# source: https://starship.rs/presets/tokyo-night
# Disable the blank line at the start of the prompt
add_newline = false

format = """
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
[](fg:#394260 bg:#212736)\
[ ](fg:#1d2230)\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "…/"
truncate_to_repo = false

[line_break]
disabled = false

[character]
success_symbol = "[](white)"
error_symbol = "[](red)"
vicmd_symbol = "[](green)"

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[aws]
disabled = true

[cmd_duration]
disabled = true

[rlang]
disabled = true

[hostname]
disabled = true

[docker_context]
disabled = true


[git_commit]
disabled = true

[git_metrics]
disabled = true

[git_state]
disabled = true

[git_status]
disabled = true

[lua]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[rust] 
disabled = true

[username]
disabled = true

