# yaml-language-server: $schema=https://dlvhdr.github.io/gh-dash/configuration/gh-dash/schema.json

# Adapted from: https://github.com/dlvhdr/dotfiles/blob/main/.config/gh-dash/config.yml
# and: https://github.com/joshmedeski/dotfiles/blob/main/.config/gh-dash/config.yml
prSections:
  - title: My PRs
    filters: is:open author:@me
  - title: My Review
    filters: is:open review-requested:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
issuesSections:
  - title: Assigned
    filters: is:open assignee:@me
  - title: Creator
    filters: author:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
  - title: Commented
    filters: is:open commenter:@me
defaults:
  view: prs
  layout:
    prs:
      repoName:
        grow: true,
        width: 10
        hidden: false

  preview:
    open: true
    width: 70
  prsLimit: 20
  issuesLimit: 20

pager:
  diff: delta
  preview:
    open: true
    width: 70
  prsLimit: 20
  issuesLimit: 20

repoPaths:
  shamindras/dotfiles: ~/DROPBOX/REPOS/dotfiles

keybindings:
  universal:
    - key: g
      command: >
        cd {{.RepoPath}} && lazygit
  prs:
    # - key: O
    #   builtin: checkout
    # - key: C
    #   command: >
    #     tmux new-window -c {{.RepoPath}} '
    #     nvim -c ":silent Octo pr edit {{.PrNumber}}"
    #     '
    - key: b
      command: cd {{.RepoPath}} && gh pr view {{.PrNumber}} --json statusCheckRollup | command jq -rcj '.statusCheckRollup.[] | select(.context == "buildkite/mono") | .targetUrl' | xargs open
    - key: a
      command: >
        cd {{.RepoPath}} && git add -A && lazygit
    - key: v
      command: >
        gh pr review --repo {{.RepoName}} --approve --body "$(gum input --prompt='Approval Comment: ')" {{.PrNumber}}

theme:
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
  colors:
    text:
      primary: "#E2E1ED"
      secondary: "#666CA6"
      inverted: "#242347"
      faint: "#3E4057"
      warning: "#F23D5C"
      success: "#3DF294"
    background:
      selected: "#39386B"
    border:
      primary: "#383B5B"
      secondary: "#39386B"
      faint: "#2B2B40"
