# yaml-language-server: $schema=https://dlvhdr.github.io/gh-dash/configuration/gh-dash/schema.json
qprSections:
  - title: My Pull Requests
    filters: is:open author:@me
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
issuesSections:
  - title: Assigned
    filters: is:open assignee:@me
  - title: Creator
    filters: author:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
  - title: Commented
    filters: is:open commenter:@me
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 15
      author:
        width: 15
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 16
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30

pager:
  diff: delta
  preview:
    open: true
    width: 70
  prsLimit: 20
  issuesLimit: 20

repoPaths:
  shamindras/dotfiles: ~/DROPBOX/REPOS/dotfiles

keybindings:
  universal:
    - key: g
      command: >
        cd {{.RepoPath}} && lazygit
  prs:
    # - key: O
    #   builtin: checkout
    # - key: C
    #   command: >
    #     tmux new-window -c {{.RepoPath}} '
    #     nvim -c ":silent Octo pr edit {{.PrNumber}}"
    #     '
    - key: b
      command: cd {{.RepoPath}} && gh pr view {{.PrNumber}} --json statusCheckRollup | command jq -rcj '.statusCheckRollup.[] | select(.context == "buildkite/mono") | .targetUrl' | xargs open
    - key: a
      command: >
        cd {{.RepoPath}} && git add -A && lazygit
    - key: v
      command: >
        gh pr review --repo {{.RepoName}} --approve --body "$(gum input --prompt='Approval Comment: ')" {{.PrNumber}}

theme:
  ui:
    sectionsShowCount: true
    table:
      compact: false
  colors:
    text:
      primary: "#E2E1ED"
      secondary: "#666CA6"
      inverted: "#242347"
      faint: "#b0b3bf"
      warning: "#F7768E"
      success: "#3DF294"
    background:
      selected: "#1b1b33"
    border:
      primary: "#383B5B"
      secondary: "#39386B"
      faint: "#2B2B40"
