# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  nerdFontsVersion: "3"
  # If true (default), file icons are shown in the file views. Only relevant if NerdFontsVersion is not empty.
  # showFileIcons: true
  # showIcons: true
  # use the mocha catpuccin theme
  # see: https://github.com/catppuccin/lazygit#usage
  theme:
    # lightTheme: false
    activeBorderColor:
      - "#a6e3a1" # Green
      - bold
    inactiveBorderColor:
      - "#cdd6f4" # Text
    optionsTextColor:
      - "#89b4fa" # Blue
    selectedLineBgColor:
      - "#313244" # Surface0
    # selectedRangeBgColor:
    #   - "#313244" # Surface0
    cherryPickedCommitBgColor:
      - "#94e2d5" # Teal
    cherryPickedCommitFgColor:
      - "#89b4fa" # Blue
    unstagedChangesColor:
      - red # Red
  # Window border style.
  # One of 'rounded' (default) | 'single' | 'double' | 'hidden'
  border: rounded
  authorColors: # in case you're not happy with the randomly assigned colour
    "shamindras": "#9db5bf"
    "SS": "#9db5bf"
  # If true, capture mouse events.
  # When mouse events are captured, it's a little harder to select text: e.g. requiring you to hold the option key when on macOS.
  mouseEvents: true # stuff relating to the UI

# use delta for git diffs
git:
  paging:
    colorArg: always
    pager: delta --dark --side-by-side --line-numbers --paging=never
    useConfig: false

# use conventional commits via commitizen
# source: https://github.com/jesseduffield/lazygit/wiki/Custom-Commands-Compendium#committing-via-commitizen-cz-c
customCommands:
  - key: "C"
    command: "git cz c"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true

# TODO switch from `vim` to `nvim`
os:
  editCommand: "vim"
  editCommandTemplate: "{{editor}} +{{line}} -- {{filename}}"
  openCommand: "open {{filename}}"

disableStartupPopups: true
quitOnTopLevelReturn: true
