# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  # stuff relating to the UI
  nerdFontsVersion: "3"
  scrollHeight: 2 # how many lines you scroll by
  scrollPastBottom: true # enable scrolling past the bottom
  sidePanelWidth: 0.3333 # number from 0 to 1
  expandFocusedSidePanel: false
  mainPanelSplitMode: "flexible" # one of 'horizontal' | 'flexible' | 'vertical'
  language: "auto" # one of 'auto' | 'en' | 'zh' | 'pl' | 'nl'
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - black
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - blue
    cherryPickedCommitBgColor:
      - blue
    cherryPickedCommitFgColor:
      - cyan
    unstagedChangesColor:
      - white
  # If true (default), file icons are shown in the file views. Only relevant if NerdFontsVersion is not empty.
  showFileIcons: true
  # Window border style.
  # One of 'rounded' (default) | 'single' | 'double' | 'hidden'
  border: single
  mouseEvents: true
  skipDiscardChangeWarning: false
  skipStashWarning: true
  # If true, show the '5 of 20' footer at the bottom of list views
  showListFooter: true
  # If true, display the files in the file views as a tree. If false, display the files as a flat list.
  # This can be toggled from within Lazygit with the '~' key, but that will not change the default.
  showFileTree: true
  # If true, show a random tip in the command log when Lazygit starts
  showRandomTip: false
  # If true, show the command log
  showCommandLog: false
  # If true, show the bottom line that contains keybinding info and useful buttons. If false, this line will be hidden except to display a loader for an in-progress action.
  showBottomLine: true
  # If true, show jump-to-window keybindings in window titles.
  showPanelJumps: true
  commandLogSize: 8
  authorColors: # in case you're not happy with the randomly assigned colour
    "shamindras": "#9db5bf"
    "SS": "#9db5bf"

# If true, display a confirmation when subprocess terminates. This allows you to
# view the output of the subprocess before returning to Lazygit.
promptToReturnFromSubprocess: false

# use delta for git diffs
git:
  paging:
    colorArg: always
    pager: delta --dark --side-by-side --line-numbers --paging=never
    useConfig: false

# use conventional commits via commitizen
# source: https://github.com/jesseduffield/lazygit/wiki/Custom-Commands-Compendium#committing-via-commitizen-cz-c
customCommands:
  - key: "C"
    command: "git cz c"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true

# TODO switch from `vim` to `nvim`
os:
  editCommand: "vim"
  editCommandTemplate: "{{editor}} +{{line}} -- {{filename}}"
  openCommand: "open {{filename}}"

disableStartupPopups: true
quitOnTopLevelReturn: true
