#!/usr/bin/env bash

# shellcheck disable=SC2034
PLUGIN_DIR="$CONFIG_DIR/plugins"
# shellcheck disable=SC2034
ITEM_DIR="$CONFIG_DIR/items"

# shellcheck disable=SC1091
source "$CONFIG_DIR/colors.sh"

# Pill dimensions
PILL_HEIGHT=24
PILL_RADIUS=12
PILL_BORDER_WIDTH=3

##### Bar Appearance #####
sketchybar --bar \
  height=30 \
  color="$BAR_COLOR" \
  shadow=off \
  position=top \
  sticky=on \
  padding_right=10 \
  padding_left=10 \
  topmost=on \
  y_offset=0 \
  blur_radius=20

##### Default Values #####
sketchybar --default \
  icon.font="JetBrainsMono Nerd Font:Bold:13.0" \
  icon.color="$TEXT" \
  label.font="JetBrainsMono Nerd Font:Bold:13.0" \
  label.color="$TEXT" \
  background.color="$BAR_COLOR" \
  background.height=22 \
  padding_left=5 \
  padding_right=5 \
  label.padding_left=4 \
  label.padding_right=4 \
  label.shadow.drawing=on \
  label.shadow.color=0x80000000 \
  label.shadow.distance=1 \
  icon.padding_left=4 \
  icon.padding_right=4

##### Left Items #####
# shellcheck disable=SC1091
source "$ITEM_DIR/front_app.sh"

##### Right Items #####
# Items are added right-to-left: first sourced = rightmost in pill.
# Desired order (left to right): workspace | wifi | volume | battery | clock
# shellcheck disable=SC1091
source "$ITEM_DIR/clock.sh"
# shellcheck disable=SC1091
source "$ITEM_DIR/battery.sh"
# shellcheck disable=SC1091
source "$ITEM_DIR/volume.sh"
# shellcheck disable=SC1091
source "$ITEM_DIR/wifi.sh"
# shellcheck disable=SC1091
source "$ITEM_DIR/workspace.sh"

##### Bracket Pills #####
sketchybar --add bracket left_pill workspace \
  --set left_pill \
  background.color="$PILL_BG" \
  background.height="$PILL_HEIGHT" \
  background.corner_radius="$PILL_RADIUS" \
  background.border_width="$PILL_BORDER_WIDTH" \
  background.border_color="$PILL_BORDER"

sketchybar --add bracket right_pill wifi volume battery clock \
  --set right_pill \
  background.color="$PILL_BG" \
  background.height="$PILL_HEIGHT" \
  background.corner_radius="$PILL_RADIUS" \
  background.border_width="$PILL_BORDER_WIDTH" \
  background.border_color="$PILL_BORDER"

##### Force Initial Update #####
sketchybar --update
