#!/usr/bin/env bash

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

source "$CONFIG_DIR/colors.sh"

##### Bar Appearance #####
sketchybar --bar \
  height=37 \
  color="$BAR_COLOR" \
  shadow=off \
  position=top \
  sticky=off \
  padding_right=10 \
  padding_left=10 \
  topmost=window

##### Default Values #####
sketchybar --default \
  icon.font="JetBrainsMono Nerd Font:Bold:14.0" \
  icon.color="$TEXT" \
  label.font="JetBrainsMono Nerd Font:Bold:14.0" \
  label.color="$TEXT" \
  background.color="$BAR_COLOR" \
  background.height=30 \
  padding_left=5 \
  padding_right=5 \
  label.padding_left=4 \
  label.padding_right=4 \
  icon.padding_left=4 \
  icon.padding_right=4

##### Items #####
source "$ITEM_DIR/workspace.sh"
source "$ITEM_DIR/front_app.sh"
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/wifi.sh"

##### Force Initial Update #####
sketchybar --update
