[[session]]
name = "play"
path = "~/Dropbox/repos/codebox"
startup_command = "~/.config/sesh/scripts/play.sh"

[[session]]
name = "dots"
path = "~/Dropbox/repos/dotfiles"
startup_command = "~/.config/sesh/scripts/dots.sh"

[[session]]
name = "career"
path = "~/Dropbox/repos/ss_applications"
startup_command = "~/.config/sesh/scripts/career.sh"

[[session]]
name = "blog"
path = "~/Dropbox/repos/ss_personal_quarto_blog"
startup_command = "~/.config/sesh/scripts/blog.sh"

[[session]]
name = "notes"
path = "~/Dropbox/notes/zk"
startup_command = "~/.config/sesh/scripts/notes.sh"

[[session]]
name = "feed"
path = "~/Downloads"
startup_command = "~/.config/sesh/scripts/feed.sh"
