set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'catppuccin/tmux#v2.1.3'
set -g @plugin 'wfxr/tmux-fzf-url'

set -g @yank_action 'copy-pipe-no-clear'

run '~/.config/tmux/plugins/tpm/tpm'
