"""books.bib generation — fully regenerated from the manifest every run.

Never hand-edited, never patched: entries are sorted by key with a fixed
field order, so an unchanged library produces a byte-identical file (clean
Dropbox history). Citation key = the filename stem verbatim (hyphens kept — legal in
bibtex/biblatex), so key and file are identical. Files whose metadata was never resolved
(grandfathered conforming names) get a best-effort entry derived from the
stem itself — populated fields only, no placeholder junk."""

import json
import os
import re
import shutil
import subprocess
import tempfile

from booklib import config

_ESCAPE = re.compile(r"(?<!\\)([&%#_$])")


def _esc(s):
    return _ESCAPE.sub(r"\\\1", s)


def _stem_fallback(stem):
    """koul-2026-nonparametric-inference -> ('Koul', '2026', 'Nonparametric inference')."""
    tokens = stem.split("-")
    for i, tok in enumerate(tokens):
        if re.fullmatch(r"(19|20)\d{2}", tok) and 0 < i < len(tokens) - 1:
            title = " ".join(tokens[i + 1 :]).capitalize()
            return tokens[i - 1].capitalize(), tok, title
    return None, None, None


def entries(manifest):
    """{key: field-dict}, one entry per distinct stem, metadata-rich row wins.

    A stem is included only while at least one file bearing it survives on
    disk (scan prunes vanished paths, so manually deleted books drop out of
    the bib on the next sweep). The metadata-rich row may itself be pathless
    — e.g. an archived djvu whose converted pdf twin carries the stem."""
    by_stem = {}
    for row in manifest.rows_with_status("applied"):
        stem = row["final_stem"]
        if not stem:
            continue
        current = by_stem.get(stem)
        if current is None or (not current["authors_json"] and row["authors_json"]):
            by_stem[stem] = row
    for stem in list(by_stem):
        alive = manifest.db.execute(
            "SELECT 1 FROM metadata m JOIN paths p USING (sha256)"
            " WHERE m.final_stem=? LIMIT 1", (stem,)
        ).fetchone()
        if not alive:
            del by_stem[stem]

    out = {}
    for stem, row in by_stem.items():
        fields = {}
        if row["authors_json"]:
            fields["author"] = " and ".join(json.loads(row["authors_json"]))
            fields["title"] = row["title"] or ""
            year = row["edition_year"]
        else:
            author, year, title = _stem_fallback(stem)
            if author:
                fields["author"] = author
            if title:
                fields["title"] = title
        if row["title"]:
            fields["title"] = row["title"]
        if year:
            fields["year"] = str(year)
        if row["publisher"]:
            fields["publisher"] = row["publisher"]
        if row["isbn13"]:
            fields["isbn"] = row["isbn13"]
        fields = {k: v for k, v in fields.items() if v}
        if fields:
            out[stem] = fields
    return out


def render(entry_map):
    lines = ["% books.bib — generated by book-librarian; do not hand-edit.", ""]
    for key in sorted(entry_map):
        fields = entry_map[key]
        lines.append(f"@book{{{key},")
        for name in ("author", "title", "year", "publisher", "isbn"):
            if name in fields:
                lines.append(f"  {name} = {{{_esc(fields[name])}}},")
        lines[-1] = lines[-1].rstrip(",")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def validate(path):
    """biber --tool gate; skipped (True) when biber isn't installed."""
    if not shutil.which("biber"):
        print("biber not found — skipping validation")
        return True
    res = subprocess.run(
        ["biber", "--tool", "--validate-datamodel", "--output-file", os.devnull, str(path)],
        capture_output=True, text=True, check=False,
    )
    # biber drops a .blg log next to the input regardless of --output-file;
    # remove it so validation temp files never litter the library root.
    blg = str(path) + ".blg"
    if os.path.exists(blg):
        os.unlink(blg)
    errors = [ln for ln in res.stdout.splitlines() if ln.startswith("ERROR")]
    for ln in errors:
        print(ln)
    return res.returncode == 0 and not errors


def generate(manifest, check_only=False):
    content = render(entries(manifest))
    fd, tmp = tempfile.mkstemp(dir=config.BOOKS_ROOT, suffix=".bib.tmp")
    try:
        with os.fdopen(fd, "w") as fh:
            fh.write(content + "\n")
        if not validate(tmp):
            print("books.bib NOT updated (validation failed)")
            return False
        if check_only:
            print(f"valid: {len(entries(manifest))} entries (check only, not written)")
            return True
        os.replace(tmp, config.BIB_PATH)
        tmp = None
        print(f"wrote {config.BIB_PATH} ({content.count('@book')} entries)")
        return True
    finally:
        if tmp and os.path.exists(tmp):
            os.unlink(tmp)
