parent: default

global_vars:
  - name: MyFirstName
    type: echo
    params:
      echo: "Shamindra"
  - name: MyLastName
    type: echo
    params:
      echo: "Shrotriya"
  - name: MyName
    type: echo
    params:
      echo: "{{MyFirstName}} {{MyLastName}}"
  - name: MyEmail
    type: echo
    params:
      echo: "shamindra.shrotriya@gmail.com"
  - name: MyNameAndEmail
    type: echo
    params:
      # echo: "Shamindra Shrotriya <shamindra.shrotriya@gmail.com>"# espanso match file
      echo: "{{MyName}} <{{MyEmail}}>"

# espanso match file
# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ";espanso"
    replace: "Espanso is working!"
  - trigger: ";#zsh"
    replace: "#!/usr/bin/env zsh"
