name: emails
parent: base

matches:
  # [em]ail [p]ersonal
  - trigger: ";emp"
    replace: "{{MyEmail}}"
  # [em]ail [w]ork
  - trigger: ";emw"
    replace: "{{MyEmail}}"
    # [em]ail with +suffix
  - trigger: ";ems"
    replace: "shamindra.shrotriya+$|$@gmail.com"
    # email [sig]nature with "Best"
  - trigger: ";sigb"
    replace: "Best,\n{{MyFirstName}}"
    # email [sig]nature with "Kind regards"
  - trigger: ";sigk"
    replace: "Kind regards,\n{{MyFirstName}}"
    # email [sig]nature with "Thanks"
  - trigger: ";sigt"
    replace: "Thanks,\n{{MyFirstName}}"
    # [mob]ile - 1
  - trigger: ";mob1"
    replace: "4159373701"
    # [mob]ile - 2
  - trigger: ";mob2"
    replace: "(415) 937 3701"
    # [mob]ile - 3
  - trigger: ";mob3"
    replace: "+1 (415) 937 3701"
