name: personal
parent: base

matches:
  # For example (Australian/UK)
  - trigger: ";ee"
    replace: ", e.g. "

  # For example (USA)
  - trigger: ";eu"
    replace: ", e.g., "

  # That is (Australian/UK)
  - trigger: ";ii"
    replace: ", i.e. "

  # That is (USA)
  - trigger: ";iu"
    replace: ", i.e., "

